<a href="https://colab.research.google.com/github/Suphattha/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [3]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [4]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [5]:
np2[0,:]

array([1, 2])

##HW 6 สร้าง Distance matrix (Euclidean) ของ np2
โดยสร้าง function สำหรับคำนวณ Euclidean Distance

---
     det Euclidean(data1,data2):

      #process

      return dist

In [6]:
def Manhattan(data1,data2) : 
      distX = abs(data1[0]-data2[0])
      distY = abs(data1[1]-data2[1])
      return distX+distY

In [7]:
Manhattan(np2[0,:],np2[1,:])

5

In [8]:
dist_mat = np.zeros((4,4))
dist_mat 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
for i in range(4) :
     for j in range(4) :
          dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])

dist_mat         

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [10]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [19]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4) :
     for j in range(4) :
          dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
        
dist_math1